### ISSUE TITLE
bard doesn't display when logging in, canvas seems wrong size ?

### ISSUE THREAD

**Issue by nodegoose** [ferrous59/nodeJS-game#1]
message me.

**Comment by ferrous59** [comment]
I think I've missed some files in the most recent commits. The canvas should create an 'unknown' sprite that can be changed by logging in, but the initial sprite is not being created.

**Comment by nodegoose** [comment]
i see, would you like to work together ? this looks like it could be good fun.

**Comment by ferrous59** [comment]
sorry, this is was more of a side project.
I'm not sure how much more I'm going to update this.
